import '@/app/index.css'
import { ThemeProvider } from '@/src/theme/ThemeProvider'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="fr">
      <ThemeProvider attribute='class' defaultTheme='system' enableSystem>
        <body>
          {children}
        </body>
      </ThemeProvider>
    </html>
  )
}
